
```{r, fig.cap="", fig.alt="Client Logo", out.width="300px",  echo=FALSE}
 include_image("https://user-images.githubusercontent.com/912733/66764939-baf14f00-eea2-11e9-8428-4b9a07334b9c.png", img_dir = "images")
```

## Executive Summary {-} 

// Edit as appropriate //

It is important to **INSERT CLIENT NAME** that they have a clear understanding of any accessibility issues for users of their website. User Vision was commissioned to perform an accessibility audit of **INSERT PLATFORM**.

The aim of the audit is to determine whether there are any accessibility barriers remaining on the site. It is designed to capture any issues so that **INSERT CLIENT NAME** can make sure that the application can be used by the widest possible audience by complying with Web Content Accessibility Guidelines (WCAG) V2.1 Level A and Level AA.
The audit was carried out on desktop (using NVDA) and iPhone (using VoiceOver). Overall, we found similar issues across both screen readers, however, we have highlighted when assistive technologies interacted differently with the site in this report.
The audit was carried out on desktop (using NVDA), iPhone and iPad (using VoiceOver). Overall, we found similar issues across both screen readers, however, we have highlighted when assistive technologies interacted differently with the site in this report.
