## How to use this report  {-}

Getting the most out of this report

- When doing a web audit, the majority of the accessibility issues will be identified within the code of the site.

- In order to present the issues correctly, we highlight the issues as we have seen them, often using browser side manipulations. 

- We have also provided practical recommendations (at code level where possible) which need to be interpreted by the web development team. 
**Do note that these code snippets have often been shortened for readability. This might involve removing class names, certain attributes, or sources that are not relevant to the issue captured.**

- As such the ‘findings’ section of the report is aimed primarily at the web development team as they will be responsible for fixing the issues. We recommend that your lead developer reads this report and is actively involved in the project. 

- The summary and next steps are written to guide the management and product owners to get an understanding of the situation and to recommend what to do next. 

- When issues occur across multiple pages findings, these may be marked as sitewide and the relevant page URLs will be highlighted. 

- We conduct audits on Google Chrome before testing on Edge and Firefox. If the issue is marked with the 'Desktop' label, the issues persist across all browsers. If the issue is unique to the browser, it is marked with the Edge, Chrome, or Firefox label. 

- We run an automated accessibility checking tool in Accessibility Insights and WAVE. These findings are indicated with the label 'Automated findings'.


## Understanding our findings  {-}
Issues found during this accessibility audit have been identified and are supported by our recommendations. The findings have been classified as follows:

| WCAG Guideline | Level of web accessibility conformance |
|:--|:--|
| WCAG 2.1 |  Level A (lowest), AA, AAA (highest) |

| Ranking         | Definition |
|:----------------|:-------------------------------------|
| Positive | An example of good practice which should be maintained.                          	                            |
| High | Prevents one or more disability groups from being able to use the site.            |
| Medium | Causes one or more disability groups significant difficulty using the site.	|
| Low | Causes one or more disability groups some inconvenience when using the site. 	    |
| Observation | Usability issue, not a WCAG issue.    	|

# (PART) Findings {-}
